import type { Direction, StrategyLeg } from '../types/strategyTypes'

export type EducationCategory =
  | 'bullish'
  | 'bearish'
  | 'neutral_income'
  | 'volatility'
  | 'time_spread'
  | 'greeks'
  | 'stock_overlay'

export type EducationLevel = 'beginner' | 'intermediate' | 'advanced'

export type StrategyEducationItem = {
  id: string
  name: string
  zhName: string
  category: EducationCategory
  level: EducationLevel
  direction: Direction | 'income'
  supportedInBuilder: boolean
  summary: string
  bestFor: string[]
  avoidWhen: string[]
  legs: string[]
  sampleLegs: StrategyLeg[]
  payoff: {
    maxLoss: string
    maxProfit: string
    breakeven: string
    shape: string
  }
  keyRisks: string[]
  teachingNotes: string[]
}

const expiry = '2026-08-21'

export const educationCategories: Record<EducationCategory, { title: string; description: string }> = {
  bullish: {
    title: '看多策略',
    description: '用于表达上涨观点，核心区别是用权利金换弹性，还是用价差控制成本和上限。',
  },
  bearish: {
    title: '看空策略',
    description: '用于表达下跌观点，重点比较最大亏损、盈利上限和对下跌速度的要求。',
  },
  neutral_income: {
    title: '中性与收租策略',
    description: '用于价格区间震荡或希望收取权利金的场景，必须重点看尾部风险和指派风险。',
  },
  volatility: {
    title: '波动率策略',
    description: '用于判断“会大动”或“不会大动”，方向不是重点，波动率和事件风险更重要。',
  },
  time_spread: {
    title: '日历与对角价差',
    description: '利用不同到期日之间的时间价值差异，收益不是固定上限，适合进阶学习。',
  },
  greeks: {
    title: 'Greeks 与波动暴露',
    description: '围绕 delta、gamma、theta、vega 做风险暴露管理，适合进阶用户理解组合风险来源。',
  },
  stock_overlay: {
    title: '持股增强与保护',
    description: '和正股仓位结合，用期权降低成本、增强收入或保护下跌风险。',
  },
}

const coreStrategyEducationContent: StrategyEducationItem[] = [
  {
    id: 'long-call',
    name: 'Long Call',
    zhName: '买入看涨',
    category: 'bullish',
    level: 'beginner',
    direction: 'bullish',
    supportedInBuilder: true,
    summary: '用有限权利金换取上涨弹性，方向判断要对，速度也要够快。',
    bestFor: ['强烈看多', '希望亏损限定为权利金', '不想直接买入正股'],
    avoidWhen: ['隐含波动率很高', '预期只是小幅上涨', '到期日太近且新手不熟悉 theta'],
    legs: ['买入 1 张看涨期权'],
    sampleLegs: [{ action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 }],
    payoff: {
      maxLoss: '支付的权利金',
      maxProfit: '理论上无限',
      breakeven: '行权价 + 权利金',
      shape: '亏损有限，超过盈亏平衡后向上斜线盈利。',
    },
    keyRisks: ['时间流逝会损耗权利金', 'IV 回落会压低期权价格', '上涨不到盈亏平衡仍可能亏损'],
    teachingNotes: ['常见选择是 30-60 DTE、约 0.45-0.65 delta。', '适合趋势明确的观点，不适合只想赌一点点上涨。'],
  },
  {
    id: 'bull-call-spread',
    name: 'Bull Call Spread',
    zhName: '牛市看涨价差',
    category: 'bullish',
    level: 'beginner',
    direction: 'bullish',
    supportedInBuilder: true,
    summary: '买入低行权价 call，同时卖出高行权价 call，降低成本并限制最大收益。',
    bestFor: ['温和到中度看多', '有明确目标价', '希望最大亏损可控'],
    avoidWhen: ['预期大幅暴涨', '目标价远高于卖出行权价', '买卖价差过宽'],
    legs: ['买入 1 张较低行权价看涨', '卖出 1 张较高行权价看涨'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '净支出权利金',
      maxProfit: '价差宽度 - 净支出',
      breakeven: '买入 call 行权价 + 净支出',
      shape: '亏损有限，盈利到卖出 call 行权价后封顶。',
    },
    keyRisks: ['收益被卖出 call 封顶', '价格横盘会受时间损耗', '目标价设置不合理会降低性价比'],
    teachingNotes: ['卖出行权价通常靠近目标价。', '比单买 call 更适合新手理解风险预算。'],
  },
  {
    id: 'bull-put-spread',
    name: 'Bull Put Spread',
    zhName: '牛市看跌价差',
    category: 'bullish',
    level: 'intermediate',
    direction: 'bullish',
    supportedInBuilder: true,
    summary: '卖出较高行权价 put，买入较低行权价 put，对“价格不跌破某区域”收取信用金。',
    bestFor: ['温和看多或不看跌', 'IV 偏高', '希望用定义风险卖方结构'],
    avoidWhen: ['不能接受指派风险', '标的可能快速下跌', '新手不了解短期权风险'],
    legs: ['卖出 1 张较高行权价看跌', '买入 1 张较低行权价看跌'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: {
      maxLoss: '价差宽度 - 收到信用金',
      maxProfit: '收到的净信用金',
      breakeven: '卖出 put 行权价 - 净信用金',
      shape: '价格在短 put 上方盈利封顶，下破保护 put 后亏损封顶。',
    },
    keyRisks: ['短 put 有提前指派风险', '下跌速度快时亏损会放大', '信用金小但尾部风险仍需控制'],
    teachingNotes: ['常见短腿选择约 0.16-0.25 delta。', '适合把“不会跌破某价位”转化为定义风险策略。'],
  },
  {
    id: 'cash-secured-put',
    name: 'Cash-Secured Put',
    zhName: '现金担保卖跌',
    category: 'stock_overlay',
    level: 'beginner',
    direction: 'income',
    supportedInBuilder: true,
    summary: '卖出 put 收权利金，同时准备现金在被指派时买入 100 股。',
    bestFor: ['愿意以更低价格买入正股', '现金充足', '想用期权改善入场价格'],
    avoidWhen: ['不想持有正股', '没有足够现金', '标的基本面不愿长期持有'],
    legs: ['卖出 1 张看跌期权，并预留 100 股现金'],
    sampleLegs: [{ action: 'sell', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 }],
    payoff: {
      maxLoss: '接近买入 100 股的下跌风险，扣除权利金',
      maxProfit: '收到的权利金',
      breakeven: '卖出 put 行权价 - 权利金',
      shape: '上涨或横盘收益封顶，下跌后风险类似持股。',
    },
    keyRisks: ['被指派后需要买入股票', '暴跌时亏损接近持股亏损', '收益上限只是权利金'],
    teachingNotes: ['不是“免费收租”，本质是带折扣的潜在买股。', '适合先问自己是否愿意按行权价持有正股。'],
  },
  {
    id: 'long-put',
    name: 'Long Put',
    zhName: '买入看跌',
    category: 'bearish',
    level: 'beginner',
    direction: 'bearish',
    supportedInBuilder: true,
    summary: '用有限权利金表达下跌观点，也可作为持股保护。',
    bestFor: ['强烈看空', '希望亏损限定为权利金', '需要保护正股下跌'],
    avoidWhen: ['IV 很高', '预期只是小幅回调', '到期日前可能横盘'],
    legs: ['买入 1 张看跌期权'],
    sampleLegs: [{ action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 }],
    payoff: {
      maxLoss: '支付的权利金',
      maxProfit: '接近行权价 - 权利金',
      breakeven: '行权价 - 权利金',
      shape: '亏损有限，跌破盈亏平衡后盈利增加。',
    },
    keyRisks: ['时间损耗', 'IV 回落', '下跌不到盈亏平衡仍可能亏损'],
    teachingNotes: ['买 put 是最直观的看空策略。', '作为保险时，要把权利金视为保护成本。'],
  },
  {
    id: 'bear-put-spread',
    name: 'Bear Put Spread',
    zhName: '熊市看跌价差',
    category: 'bearish',
    level: 'beginner',
    direction: 'bearish',
    supportedInBuilder: true,
    summary: '买入高行权价 put，卖出低行权价 put，降低看空成本并限制收益。',
    bestFor: ['温和到中度看空', '有明确下跌目标', '希望定义风险'],
    avoidWhen: ['预期崩盘式下跌', '低行权价 put 收益封顶不符合目标', '价差不够流动'],
    legs: ['买入 1 张较高行权价看跌', '卖出 1 张较低行权价看跌'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '净支出权利金',
      maxProfit: '价差宽度 - 净支出',
      breakeven: '买入 put 行权价 - 净支出',
      shape: '亏损有限，下跌到卖出 put 后盈利封顶。',
    },
    keyRisks: ['收益被卖出 put 封顶', '横盘时仍受时间损耗', '目标价需要和短 put 匹配'],
    teachingNotes: ['比单买 put 成本更低。', '适合明确的阶段性下跌观点。'],
  },
  {
    id: 'bear-call-spread',
    name: 'Bear Call Spread',
    zhName: '熊市看涨价差',
    category: 'bearish',
    level: 'intermediate',
    direction: 'bearish',
    supportedInBuilder: true,
    summary: '卖出较低行权价 call，买入较高行权价 call，对“价格不涨破某区域”收取信用金。',
    bestFor: ['温和看空或不看涨', 'IV 偏高', '希望定义风险卖方结构'],
    avoidWhen: ['标的可能大涨', '不理解短 call 指派风险', '价差宽度超过风险预算'],
    legs: ['卖出 1 张较低行权价看涨', '买入 1 张较高行权价看涨'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: {
      maxLoss: '价差宽度 - 收到信用金',
      maxProfit: '收到的净信用金',
      breakeven: '卖出 call 行权价 + 净信用金',
      shape: '价格在短 call 下方盈利封顶，上破保护 call 后亏损封顶。',
    },
    keyRisks: ['短 call 有提前指派风险', '上涨突破短腿后亏损加速', '信用金不代表低风险'],
    teachingNotes: ['适合用来表达上方压力位观点。', '新手应优先选择定义风险而不是裸卖 call。'],
  },
  {
    id: 'iron-condor',
    name: 'Iron Condor',
    zhName: '铁鹰价差',
    category: 'neutral_income',
    level: 'intermediate',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '同时卖出看跌价差和看涨价差，押注价格留在区间内。',
    bestFor: ['区间震荡', 'IV 偏高', '希望定义风险收取权利金'],
    avoidWhen: ['重大财报或事件前', '预期趋势突破', '买卖价差过宽'],
    legs: ['卖出 OTM put', '买入更低 put', '卖出 OTM call', '买入更高 call'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
      { action: 'sell', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: {
      maxLoss: '单侧价差宽度 - 净信用金',
      maxProfit: '收到的净信用金',
      breakeven: '下方短 put - 信用金；上方短 call + 信用金',
      shape: '中间区间盈利，两端突破后亏损封顶。',
    },
    keyRisks: ['突破区间会亏损', '短腿指派风险', '四腿结构执行成本更高'],
    teachingNotes: ['不是单纯“高胜率”，收益风险比通常较小。', '常见管理规则是收取 40-60% 信用金后复查。'],
  },
  {
    id: 'iron-butterfly',
    name: 'Iron Butterfly',
    zhName: '铁蝶式',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '卖出 ATM straddle，同时买入两侧保护翼，押注价格钉在中间。',
    bestFor: ['强烈认为价格接近某一点', 'IV 偏高', '能主动管理'],
    avoidWhen: ['预期会大幅波动', '新手不熟悉四腿结构', '流动性差'],
    legs: ['卖出 ATM put', '买入下方 put', '卖出 ATM call', '买入上方 call'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
      { action: 'sell', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: {
      maxLoss: '翼宽 - 净信用金',
      maxProfit: '收到的净信用金',
      breakeven: '中心价上下减/加净信用金',
      shape: '中心点收益最高，离中心越远收益下降，两侧亏损封顶。',
    },
    keyRisks: ['盈利区间窄', '价格偏离中心会快速损耗利润', '四腿成交质量重要'],
    teachingNotes: ['比 iron condor 更集中，收益更高但容错更低。', '适合有明确 pin 价判断的进阶用户。'],
  },
  {
    id: 'long-straddle',
    name: 'Long Straddle',
    zhName: '买入跨式',
    category: 'volatility',
    level: 'intermediate',
    direction: 'volatile',
    supportedInBuilder: true,
    summary: '同时买入同一行权价 call 和 put，押注大幅波动，不押方向。',
    bestFor: ['预期大幅波动', '事件前后方向不确定', '愿意承担双边权利金成本'],
    avoidWhen: ['IV 已极高且事件后可能 IV crush', '预期波动不够大', '到期日太近'],
    legs: ['买入 ATM call', '买入 ATM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
    ],
    payoff: {
      maxLoss: '两边权利金总和',
      maxProfit: '上方理论无限，下方接近行权价扣成本',
      breakeven: '行权价 ± 总权利金',
      shape: '中间亏损最大，两边大幅移动才盈利。',
    },
    keyRisks: ['需要足够大的真实波动', 'IV crush 会伤害买方', '双边权利金成本高'],
    teachingNotes: ['适合先比较 expected move 和两端盈亏平衡。', '不是“涨跌都赚钱”，而是“涨跌足够多才赚钱”。'],
  },
  {
    id: 'long-strangle',
    name: 'Long Strangle',
    zhName: '买入宽跨式',
    category: 'volatility',
    level: 'intermediate',
    direction: 'volatile',
    supportedInBuilder: true,
    summary: '买入 OTM call 和 OTM put，成本低于跨式，但需要更大波动。',
    bestFor: ['预期大波动但想降低成本', '可接受更远盈亏平衡', '事件波动交易'],
    avoidWhen: ['标的波动普通', 'OTM 合约流动性弱', '希望小波动也能盈利'],
    legs: ['买入 OTM call', '买入 OTM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '两边权利金总和',
      maxProfit: '上方理论无限，下方接近 put 行权价扣成本',
      breakeven: '下方 put 行权价 - 总权利金；上方 call 行权价 + 总权利金',
      shape: '中间亏损，只有突破更远两侧才盈利。',
    },
    keyRisks: ['盈亏平衡更远', 'OTM 合约滑点可能更大', '仍受 theta 和 IV 回落影响'],
    teachingNotes: ['比 straddle 便宜，但不是更容易赚钱。', '适合用图直观看到两端距离。'],
  },
  {
    id: 'long-call-butterfly',
    name: 'Long Call Butterfly',
    zhName: '看涨蝶式',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '用三个 call 构造低成本窄区间策略，价格落在中间行权价附近收益最高。',
    bestFor: ['有精确目标价', '希望低成本定义风险', '预期价格到期靠近某点'],
    avoidWhen: ['预期趋势很强', '没有明确目标价', '腿数太多导致执行成本高'],
    legs: ['买入低行权价 call', '卖出 2 张中间 call', '买入高行权价 call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 95, expiration: expiry, quantity: 1, premium: 7 },
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 2, premium: 4 },
      { action: 'buy', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '净支出权利金',
      maxProfit: '翼宽 - 净支出',
      breakeven: '低行权价 + 净支出；高行权价 - 净支出',
      shape: '中间尖峰盈利，两侧亏损有限。',
    },
    keyRisks: ['利润区间窄', '需要精确目标价', '三腿成交难度更高'],
    teachingNotes: ['适合教学中展示“目标价策略”。', '不是方向越对越赚，超过上方盈亏平衡也会回到亏损。'],
  },
  {
    id: 'long-put-butterfly',
    name: 'Long Put Butterfly',
    zhName: '看跌蝶式',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '用三个 put 构造低成本窄区间策略，适合目标价在下方或中间的场景。',
    bestFor: ['有精确下方目标价', '希望低成本定义风险', '预期价格到期靠近某点'],
    avoidWhen: ['预期单边大跌', '没有明确目标', '流动性不足'],
    legs: ['买入低行权价 put', '卖出 2 张中间 put', '买入高行权价 put'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 100, expiration: expiry, quantity: 2, premium: 4 },
      { action: 'buy', right: 'put', strike: 105, expiration: expiry, quantity: 1, premium: 7 },
    ],
    payoff: {
      maxLoss: '净支出权利金',
      maxProfit: '翼宽 - 净支出',
      breakeven: '低行权价 + 净支出；高行权价 - 净支出',
      shape: '中间尖峰盈利，两侧亏损有限。',
    },
    keyRisks: ['利润区间窄', '目标偏差会导致收益快速下降', '多腿执行成本'],
    teachingNotes: ['和 call butterfly 的到期盈亏形态接近。', '选择 call 还是 put 更多取决于报价和流动性。'],
  },
  {
    id: 'short-straddle',
    name: 'Short Straddle',
    zhName: '卖出跨式',
    category: 'volatility',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '同时卖出 ATM call 和 put，押注价格不动，风险无上限。',
    bestFor: ['高级用户', 'IV 极高且有管理计划', '能承受尾部风险'],
    avoidWhen: ['新手', '重大事件前', '账户无法承受无上限风险'],
    legs: ['卖出 ATM call', '卖出 ATM put'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
    ],
    payoff: {
      maxLoss: '无上限',
      maxProfit: '收到的总权利金',
      breakeven: '行权价 ± 总权利金',
      shape: '中间盈利，两侧大幅移动亏损扩大。',
    },
    keyRisks: ['尾部风险无上限', '保证金要求高', '短腿指派风险'],
    teachingNotes: ['教学中必须明确：高胜率不等于低风险。', '不适合作为默认推荐给新手。'],
  },
  {
    id: 'short-strangle',
    name: 'Short Strangle',
    zhName: '卖出宽跨式',
    category: 'volatility',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '卖出 OTM call 和 OTM put，区间更宽但仍有无上限风险。',
    bestFor: ['高级用户', '高 IV 区间震荡', '有严格风控计划'],
    avoidWhen: ['新手', '单边突破风险高', '不接受保证金和指派风险'],
    legs: ['卖出 OTM call', '卖出 OTM put'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '无上限',
      maxProfit: '收到的总权利金',
      breakeven: '下方 put 行权价 - 总权利金；上方 call 行权价 + 总权利金',
      shape: '宽区间内盈利，两端突破后亏损扩大。',
    },
    keyRisks: ['无上限尾部风险', '保证金波动', '黑天鹅行情风险'],
    teachingNotes: ['比 short straddle 范围宽，但收入也低。', '必须放在高级风险教育区域。'],
  },
  {
    id: 'covered-call',
    name: 'Covered Call',
    zhName: '备兑看涨',
    category: 'stock_overlay',
    level: 'beginner',
    direction: 'income',
    supportedInBuilder: false,
    summary: '持有 100 股正股，同时卖出 call 收权利金，换取上方收益被封顶。',
    bestFor: ['已经持股', '愿意在目标价卖出股票', '希望增强收入'],
    avoidWhen: ['不想卖出股票', '预期大幅上涨', '持股数量不足 100 股'],
    legs: ['持有 100 股正股', '卖出 1 张看涨期权'],
    sampleLegs: [{ action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 }],
    payoff: {
      maxLoss: '正股下跌风险，扣除权利金缓冲',
      maxProfit: '行权价以上正股收益封顶 + 权利金',
      breakeven: '持股成本 - 权利金',
      shape: '下跌仍亏损，上涨到短 call 后收益封顶。',
    },
    keyRisks: ['错过大涨收益', '下跌保护有限', '可能被提前行权卖出股票'],
    teachingNotes: ['不是保护性策略，而是收入增强策略。', '适合“到了某价我愿意卖”的持股人。'],
  },
  {
    id: 'protective-put',
    name: 'Protective Put',
    zhName: '保护性看跌',
    category: 'stock_overlay',
    level: 'beginner',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '持有正股，同时买入 put，给持仓买保险。',
    bestFor: ['已有持股但担心下跌', '愿意支付保护成本', '重大事件前控制尾部风险'],
    avoidWhen: ['不愿支付权利金', 'IV 极高导致保险太贵', '保护期限和风险事件不匹配'],
    legs: ['持有 100 股正股', '买入 1 张看跌期权'],
    sampleLegs: [{ action: 'buy', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 }],
    payoff: {
      maxLoss: '持股成本 - put 行权价 + 权利金',
      maxProfit: '正股上涨理论上无限，扣除保险成本',
      breakeven: '持股成本 + 权利金',
      shape: '下方亏损被 put 限制，上方保留正股上涨。',
    },
    keyRisks: ['保险成本会拖累收益', '保护到期后失效', '保护价位选择过低可能缓冲不足'],
    teachingNotes: ['适合解释“期权保险”的直觉。', '重点看保险成本占持仓比例是否合理。'],
  },
  {
    id: 'call-calendar-spread',
    name: 'Call Calendar Spread',
    zhName: '看涨日历价差',
    category: 'time_spread',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '卖出近月 call，买入同 strike 远月 call，利用近月时间衰减。',
    bestFor: ['短期不大动，长期保留方向弹性', '理解 IV term structure', '能管理近月到期'],
    avoidWhen: ['不理解不同到期日风险', '近月可能被突破', '事件导致 IV 结构突变'],
    legs: ['卖出近月 call', '买入远月同 strike call'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 100, expiration: '2026-07-31', quantity: 1, premium: 3 },
      { action: 'buy', right: 'call', strike: 100, expiration: '2026-08-21', quantity: 1, premium: 5 },
    ],
    payoff: {
      maxLoss: '净支出权利金',
      maxProfit: '可变，取决于近月到期时远月剩余价值',
      breakeven: '可变，不是固定单点',
      shape: '近月到期时在中心行权价附近通常最有利。',
    },
    keyRisks: ['收益可变不易直观', '短腿指派风险', 'IV term structure 变化'],
    teachingNotes: ['教学图应标注“不是标准到期固定盈亏图”。', '适合进阶页面，不适合新手默认推荐。'],
  },
  {
    id: 'put-calendar-spread',
    name: 'Put Calendar Spread',
    zhName: '看跌日历价差',
    category: 'time_spread',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: true,
    summary: '卖出近月 put，买入同 strike 远月 put，利用近月时间衰减并带下方倾向。',
    bestFor: ['短期价格接近某价', '长期仍需下方保护或弹性', '理解日历价差'],
    avoidWhen: ['不接受短 put 指派', '前腿可能深度实值', 'IV 结构不利'],
    legs: ['卖出近月 put', '买入远月同 strike put'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 100, expiration: '2026-07-31', quantity: 1, premium: 3 },
      { action: 'buy', right: 'put', strike: 100, expiration: '2026-08-21', quantity: 1, premium: 5 },
    ],
    payoff: {
      maxLoss: '净支出权利金',
      maxProfit: '可变',
      breakeven: '可变',
      shape: '近月到期时价格靠近 strike 通常更有利。',
    },
    keyRisks: ['短 put 指派风险', '收益可变', 'IV term structure 风险'],
    teachingNotes: ['和 call calendar 机制类似。', '强调前腿到期管理，而不是等所有腿一起到期。'],
  },
  {
    id: 'call-diagonal-spread',
    name: 'Call Diagonal Spread',
    zhName: '看涨对角价差',
    category: 'time_spread',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: true,
    summary: '买入远月 call，卖出近月更高行权价 call，同时利用方向和时间价值。',
    bestFor: ['温和看多', '希望降低远月 call 成本', '能管理短腿滚动'],
    avoidWhen: ['预期快速大涨', '不想处理近月短腿', '不了解日历和价差组合风险'],
    legs: ['买入远月 call', '卖出近月更高 strike call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: '2026-08-21', quantity: 1, premium: 6 },
      { action: 'sell', right: 'call', strike: 110, expiration: '2026-07-31', quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '通常接近净支出，但实际风险受短腿管理影响',
      maxProfit: '可变',
      breakeven: '可变',
      shape: '收益取决于近月到期价格、远月剩余价值和 IV。',
    },
    keyRisks: ['收益路径依赖', '短 call 被突破后的管理', 'IV 和时间结构变化'],
    teachingNotes: ['这是进阶策略，不应用固定 max profit 简化。', '适合教学中展示“滚动短腿”的思想。'],
  },
  {
    id: 'put-diagonal-spread',
    name: 'Put Diagonal Spread',
    zhName: '看跌对角价差',
    category: 'time_spread',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: true,
    summary: '买入远月 put，卖出近月更低行权价 put，同时利用下跌观点和时间价值。',
    bestFor: ['温和看空', '希望降低远月 put 成本', '能管理短腿'],
    avoidWhen: ['预期快速暴跌', '不接受短 put 指派', '不了解路径依赖'],
    legs: ['买入远月 put', '卖出近月更低 strike put'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 100, expiration: '2026-08-21', quantity: 1, premium: 6 },
      { action: 'sell', right: 'put', strike: 90, expiration: '2026-07-31', quantity: 1, premium: 2 },
    ],
    payoff: {
      maxLoss: '通常接近净支出，但实际风险受短腿管理影响',
      maxProfit: '可变',
      breakeven: '可变',
      shape: '收益取决于近月到期价格、远月剩余价值和 IV。',
    },
    keyRisks: ['短 put 指派风险', '收益可变', '需要管理近月短腿'],
    teachingNotes: ['比普通 bear put spread 更复杂。', '教学中应明确“可变”不等于计算错误。'],
  },
]

const advancedStrategyEducationContent: StrategyEducationItem[] = [
  {
    id: 'short-put',
    name: 'Short Put',
    zhName: '卖出看跌',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'income',
    supportedInBuilder: false,
    summary: '卖出 put 收权利金，本质是愿意在行权价买入股票。',
    bestFor: ['愿意接股', 'IV 偏高', '有足够保证金或现金'],
    avoidWhen: ['不想持股', '标的可能跳空下跌', '账户无法承受指派'],
    legs: ['卖出 1 张看跌期权'],
    sampleLegs: [{ action: 'sell', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 }],
    payoff: { maxLoss: '很高，接近持股下跌风险', maxProfit: '收到的权利金', breakeven: '行权价 - 权利金', shape: '横盘或上涨收益封顶，下跌风险扩大。' },
    keyRisks: ['指派风险', '保证金波动', '暴跌时亏损远大于权利金'],
    teachingNotes: ['新手更适合先看现金担保卖跌或 bull put spread。'],
  },
  {
    id: 'short-call',
    name: 'Short Call',
    zhName: '卖出看涨',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'income',
    supportedInBuilder: false,
    summary: '裸卖 call 收权利金，理论亏损无上限。',
    bestFor: ['高级用户', '有严格风控和保证金管理', '明确不看涨'],
    avoidWhen: ['新手', '可能大涨的标的', '无法承受无上限亏损'],
    legs: ['卖出 1 张看涨期权'],
    sampleLegs: [{ action: 'sell', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 3 }],
    payoff: { maxLoss: '无上限', maxProfit: '收到的权利金', breakeven: '行权价 + 权利金', shape: '价格低于行权价盈利封顶，上涨后亏损无上限。' },
    keyRisks: ['无上限风险', '保证金要求高', '提前指派风险'],
    teachingNotes: ['产品里应作为风险教育，不应默认推荐给普通用户。'],
  },
  {
    id: 'collar',
    name: 'Collar',
    zhName: '领口策略',
    category: 'stock_overlay',
    level: 'intermediate',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '持股时买 put 保护下跌，同时卖 call 补贴保险成本。',
    bestFor: ['已有持股', '希望限制下跌', '愿意放弃部分上行'],
    avoidWhen: ['不想上方收益封顶', '保护成本和卖 call 收入不匹配', '没有正股仓位'],
    legs: ['持有 100 股正股', '买入保护 put', '卖出备兑 call'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '正股下跌被 put 限制，仍有保护成本', maxProfit: '上方被 short call 封顶', breakeven: '持股成本 + 净保险成本', shape: '下方有地板，上方有天花板。' },
    keyRisks: ['错过大涨', '保护期限有限', '提前指派'],
    teachingNotes: ['适合讲“用上方收益换下方保护”。'],
  },
  {
    id: 'synthetic-long-stock',
    name: 'Synthetic Long Stock',
    zhName: '合成多头股票',
    category: 'greeks',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '买 call、卖同 strike put，构造接近持有股票的 delta 暴露。',
    bestFor: ['想理解 put-call parity', '需要接近 +100 delta', '高级组合构造'],
    avoidWhen: ['不接受指派或保证金', '不了解合成仓位', '只想控制最大亏损'],
    legs: ['买入 ATM call', '卖出 ATM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
    ],
    payoff: { maxLoss: '接近持股下跌风险', maxProfit: '理论上无限', breakeven: '接近行权价加净成本', shape: '盈亏形态接近股票多头。' },
    keyRisks: ['下跌风险大', '短 put 指派', '保证金要求'],
    teachingNotes: ['这是 delta 教学的重要策略，不适合新手直接交易。'],
  },
  {
    id: 'synthetic-short-stock',
    name: 'Synthetic Short Stock',
    zhName: '合成空头股票',
    category: 'greeks',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '卖 call、买同 strike put，构造接近做空股票的 delta 暴露。',
    bestFor: ['想获得接近 -100 delta', '理解合成空头', '高级风险管理'],
    avoidWhen: ['不接受无上限上行风险', '不熟悉保证金', '新手'],
    legs: ['卖出 ATM call', '买入 ATM put'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
    ],
    payoff: { maxLoss: '理论上无上限', maxProfit: '接近行权价扣净成本', breakeven: '接近行权价加净成本', shape: '盈亏形态接近股票空头。' },
    keyRisks: ['上涨风险无上限', '短 call 指派', '保证金波动'],
    teachingNotes: ['适合解释 delta 暴露和合成仓位。'],
  },
  {
    id: 'bullish-risk-reversal',
    name: 'Bullish Risk Reversal',
    zhName: '看涨风险逆转',
    category: 'greeks',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '买 OTM call、卖 OTM put，用下方接股风险换取上方上涨暴露。',
    bestFor: ['强看多', '愿意低位接股', '想降低或抵消买 call 成本'],
    avoidWhen: ['不接受下跌指派', '账户保证金不足', '标的尾部风险大'],
    legs: ['买入 OTM call', '卖出 OTM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '下跌风险很高', maxProfit: '理论上无限', breakeven: '取决于净成本和两侧 strike', shape: '上方有凸性，下方承担短 put 风险。' },
    keyRisks: ['短 put 指派', '下跌风险大', '保证金要求'],
    teachingNotes: ['不是低风险看涨，而是用下方义务换上方权利。'],
  },
  {
    id: 'bearish-risk-reversal',
    name: 'Bearish Risk Reversal',
    zhName: '看跌风险逆转',
    category: 'greeks',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '买 OTM put、卖 OTM call，用上方风险换取下方下跌暴露。',
    bestFor: ['强看空', '想降低买 put 成本', '高级用户'],
    avoidWhen: ['不接受上涨无上限风险', '标的可能大涨', '新手'],
    legs: ['买入 OTM put', '卖出 OTM call'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '上涨风险理论无上限', maxProfit: '接近 put 行权价扣净成本', breakeven: '取决于净成本和两侧 strike', shape: '下方受益，上方承担短 call 风险。' },
    keyRisks: ['短 call 无上限风险', '指派风险', '保证金要求'],
    teachingNotes: ['适合作为风险逆转教学，不适合默认推荐。'],
  },
  {
    id: 'call-ratio-spread',
    name: 'Call Ratio Spread',
    zhName: '看涨比例价差',
    category: 'bullish',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '买 1 张低 strike call，卖 2 张高 strike call，押注温和上涨。',
    bestFor: ['温和看涨', '希望降低成本', '能管理上方裸 call 风险'],
    avoidWhen: ['可能大涨', '不接受无上限风险', '新手'],
    legs: ['买入 1 张较低 call', '卖出 2 张较高 call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 2, premium: 2 },
    ],
    payoff: { maxLoss: '取决于净成本；上方可能无上限', maxProfit: '通常在短 call strike 附近最高', breakeven: '可能有两个，取决于净成本', shape: '温和上涨有利，大涨反而危险。' },
    keyRisks: ['裸短 call 风险', '上方亏损可能无上限', '成交和保证金复杂'],
    teachingNotes: ['和普通 bull call spread 最大区别是多卖了一张 call。'],
  },
  {
    id: 'put-ratio-spread',
    name: 'Put Ratio Spread',
    zhName: '看跌比例价差',
    category: 'bearish',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '买 1 张高 strike put，卖 2 张低 strike put，押注温和下跌。',
    bestFor: ['温和看跌', '希望降低买 put 成本', '能管理下方短 put 风险'],
    avoidWhen: ['可能暴跌', '不接受接股或保证金风险', '新手'],
    legs: ['买入 1 张较高 put', '卖出 2 张较低 put'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 2, premium: 2 },
    ],
    payoff: { maxLoss: '下方风险很高', maxProfit: '通常在短 put strike 附近最高', breakeven: '可能有两个，取决于净成本', shape: '温和下跌有利，暴跌风险扩大。' },
    keyRisks: ['短 put 指派', '暴跌风险', '保证金复杂'],
    teachingNotes: ['适合进阶理解“方向对也可能因幅度过大而变差”。'],
  },
  {
    id: 'call-backspread',
    name: 'Call Backspread',
    zhName: '看涨反向比例价差',
    category: 'volatility',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '卖 1 张低 strike call，买 2 张高 strike call，押注大涨和正 gamma。',
    bestFor: ['预期大涨', '想获得上方凸性', '能接受中间亏损区'],
    avoidWhen: ['只预期小涨', '不理解中间亏损带', '流动性弱'],
    legs: ['卖出 1 张较低 call', '买入 2 张较高 call'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 2, premium: 2 },
    ],
    payoff: { maxLoss: '通常在高 strike 附近最大', maxProfit: '理论上无限', breakeven: '通常有上方盈亏平衡', shape: '小涨可能亏，大涨才受益。' },
    keyRisks: ['中间区域亏损', '执行成本', '需大幅移动'],
    teachingNotes: ['这是正 gamma、上方凸性策略。'],
  },
  {
    id: 'put-backspread',
    name: 'Put Backspread',
    zhName: '看跌反向比例价差',
    category: 'volatility',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '卖 1 张高 strike put，买 2 张低 strike put，押注大跌和正 gamma。',
    bestFor: ['预期大跌', '想获得下方凸性', '高级波动交易'],
    avoidWhen: ['只预期小跌', '不理解中间亏损带', '价差很宽'],
    legs: ['卖出 1 张较高 put', '买入 2 张较低 put'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 2, premium: 2 },
    ],
    payoff: { maxLoss: '通常在低 strike 附近最大', maxProfit: '下方高但有限', breakeven: '通常有下方盈亏平衡', shape: '小跌可能亏，大跌才受益。' },
    keyRisks: ['中间亏损区', '需要大幅下跌', '多腿执行'],
    teachingNotes: ['适合解释 crash hedge 和正 gamma。'],
  },
  {
    id: 'long-call-condor',
    name: 'Long Call Condor',
    zhName: '看涨秃鹰',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '四个不同 strike 的 call 组成宽平台蝶式，押注价格落在中间区间。',
    bestFor: ['有目标区间', '希望定义风险', '想比蝶式更宽容'],
    avoidWhen: ['预期单边大动', '执行成本太高', '流动性不足'],
    legs: ['买低 call', '卖中低 call', '卖中高 call', '买高 call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 90, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'call', strike: 120, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '净支出', maxProfit: '中间平台收益', breakeven: '上下两个盈亏平衡', shape: '中间区间收益平台，两侧亏损有限。' },
    keyRisks: ['执行复杂', '利润有限', '需要价格落入区间'],
    teachingNotes: ['可以看作更宽的 butterfly。'],
  },
  {
    id: 'long-put-condor',
    name: 'Long Put Condor',
    zhName: '看跌秃鹰',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '用 put 构造的区间型定义风险策略，盈亏形态接近 call condor。',
    bestFor: ['目标区间明确', 'put 流动性更好', '希望定义风险'],
    avoidWhen: ['预期强趋势', '多腿滑点大', '新手'],
    legs: ['买低 put', '卖中低 put', '卖中高 put', '买高 put'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
      { action: 'sell', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 110, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'put', strike: 120, expiration: expiry, quantity: 1, premium: 12 },
    ],
    payoff: { maxLoss: '净支出', maxProfit: '中间平台收益', breakeven: '上下两个盈亏平衡', shape: '中间区间收益平台，两侧亏损有限。' },
    keyRisks: ['多腿成交', '利润区有限', '目标区间判断'],
    teachingNotes: ['选择 call 还是 put condor 主要看报价和流动性。'],
  },
  {
    id: 'jade-lizard',
    name: 'Jade Lizard',
    zhName: '玉蜥蜴',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '卖 put，同时卖 call spread，希望获得足够信用金以消除上方风险。',
    bestFor: ['不看跌或温和看多', 'IV 偏高', '高级信用策略'],
    avoidWhen: ['标的可能大跌', '信用金不足以覆盖 call spread 宽度', '不接受短 put 风险'],
    legs: ['卖出 OTM put', '卖出 OTM call', '买入更高 call'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'call', strike: 115, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '下方短 put 风险很高', maxProfit: '收到的净信用金', breakeven: '下方 put strike - 信用金', shape: '上方风险可被信用金抵消，下方仍有风险。' },
    keyRisks: ['短 put 下方风险', '结构条件要求严格', '保证金要求'],
    teachingNotes: ['核心不是名字，而是“信用金是否大于 call spread 宽度”。'],
  },
  {
    id: 'broken-wing-butterfly',
    name: 'Broken Wing Butterfly',
    zhName: '断翼蝶式',
    category: 'neutral_income',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '不等宽蝶式，把一侧风险/收益重新分配，常用于降低成本或形成信用结构。',
    bestFor: ['有偏向的区间判断', '想减少一侧风险', '能理解非对称 payoff'],
    avoidWhen: ['新手', '不理解翼宽不等', '流动性差'],
    legs: ['买入一侧保护腿', '卖出 2 张中间腿', '买入另一侧更远保护腿'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 95, expiration: expiry, quantity: 1, premium: 7 },
      { action: 'sell', right: 'call', strike: 100, expiration: expiry, quantity: 2, premium: 4 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '取决于断翼方向和净借贷', maxProfit: '通常在中间 strike 附近最高', breakeven: '一个或两个，取决于结构', shape: '非对称蝶式，一侧风险更大或更小。' },
    keyRisks: ['非对称风险容易误读', '多腿执行', '目标价要求高'],
    teachingNotes: ['适合解释“同样是蝶式，翼宽改变会改变风险分布”。'],
  },
  {
    id: 'delta-hedged-long-gamma',
    name: 'Delta-Hedged Long Gamma',
    zhName: 'Delta 对冲正 Gamma',
    category: 'greeks',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '持有正 gamma 期权结构，并用股票动态对冲 delta，押注实现波动超过成本。',
    bestFor: ['理解动态对冲', '预期实现波动高', '能频繁管理'],
    avoidWhen: ['无法调仓', '交易成本高', '不了解 gamma/theta 交换'],
    legs: ['通常买入 straddle 或 strangle', '用股票动态对冲 delta'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
    ],
    payoff: { maxLoss: '期权权利金加对冲成本', maxProfit: '取决于波动和对冲执行', breakeven: '动态路径相关', shape: '不是静态到期图，收益来自波动路径。' },
    keyRisks: ['theta 成本', '对冲成本', '路径依赖'],
    teachingNotes: ['这是 Greeks 教育，不应当简化成普通静态策略。'],
  },
  {
    id: 'theta-income-basket',
    name: 'Theta Income Basket',
    zhName: 'Theta 收益组合',
    category: 'greeks',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '用信用价差、铁鹰等结构组合获取正 theta，同时控制尾部风险。',
    bestFor: ['理解卖方组合', 'IV 偏高', '能做仓位分散和止损'],
    avoidWhen: ['黑天鹅风险高', '没有组合风控', '只看每日 theta 收入'],
    legs: ['通常由多个定义风险信用策略组成'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
      { action: 'sell', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '定义风险但可能多笔同时亏损', maxProfit: '收到的净信用金', breakeven: '取决于组合结构', shape: '区间内收租，突破后亏损。' },
    keyRisks: ['尾部相关性', '连续小赚一次大亏', '保证金和流动性'],
    teachingNotes: ['正 theta 不是免费收益，它通常来自承担 gamma/尾部风险。'],
  },
  {
    id: 'vega-long-calendar',
    name: 'Vega Long Calendar',
    zhName: 'Vega 多头日历',
    category: 'greeks',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '通过买远月卖近月获得相对正 vega，关注 IV term structure 变化。',
    bestFor: ['预期远月 IV 上升或保持', '短期价格不大动', '理解期限结构'],
    avoidWhen: ['近月事件 IV crush', '价格快速突破短腿', '不理解日历收益可变'],
    legs: ['卖出近月期权', '买入远月同或相近 strike 期权'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 100, expiration: '2026-07-31', quantity: 1, premium: 3 },
      { action: 'buy', right: 'call', strike: 100, expiration: '2026-08-21', quantity: 1, premium: 5 },
    ],
    payoff: { maxLoss: '净支出', maxProfit: '可变', breakeven: '可变', shape: '受价格、时间和 IV 三者共同影响。' },
    keyRisks: ['IV term structure 变化', '短腿被突破', '路径依赖'],
    teachingNotes: ['适合把 calendar 和 vega 风险联系起来。'],
  },
]

const marketCatalogStrategyContent: StrategyEducationItem[] = [
  {
    id: 'fig-leaf',
    name: 'Fig Leaf',
    zhName: '无花果叶策略',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '买入远月 ITM call 作为股票替代，同时卖出近月 OTM call 收入。',
    bestFor: ['想降低持股资金占用', '温和看多', '能管理短 call'],
    avoidWhen: ['不理解 LEAPS 风险', '预期短期暴涨', '短腿流动性弱'],
    legs: ['买入远月 ITM call', '卖出近月 OTM call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 80, expiration: '2026-12-18', quantity: 1, premium: 24 },
      { action: 'sell', right: 'call', strike: 110, expiration: '2026-08-21', quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '远月 call 净成本', maxProfit: '可变，上方受短 call 管理影响', breakeven: '可变', shape: '类似低资金股票替代叠加备兑卖 call。' },
    keyRisks: ['远月期权时间价值', '短 call 被突破', '收益路径依赖'],
    teachingNotes: ['可理解为 poor man covered call。'],
  },
  {
    id: 'covered-put',
    name: 'Covered Put',
    zhName: '备兑看跌',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '持有股票空头，同时卖出 put 收权利金。',
    bestFor: ['已有空头股票仓位', '温和看空或中性', '希望增加空头收入'],
    avoidWhen: ['不做空股票', '可能快速反弹', '不了解借券和空头风险'],
    legs: ['做空 100 股', '卖出 1 张 put'],
    sampleLegs: [{ action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 }],
    payoff: { maxLoss: '理论上无上限', maxProfit: '下方收益被 short put 封顶', breakeven: '空头成本 + 权利金', shape: '下跌收益封顶，上涨风险无上限。' },
    keyRisks: ['空头上行风险', '借券成本', '短 put 指派'],
    teachingNotes: ['这是 covered call 的空头股票镜像。'],
  },
  {
    id: 'covered-ratio-spread',
    name: 'Covered Ratio Spread',
    zhName: '备兑比例价差',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '持股后买 1 张 call、卖 2 张更高 strike call，增强目标价附近收益。',
    bestFor: ['持股且有明确上方目标', '愿意在高位卖出', '能管理多卖 call'],
    avoidWhen: ['预期大幅突破', '不想限制持股上行', '不了解比例结构'],
    legs: ['持有 100 股', '买入 1 张 call', '卖出 2 张更高 call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 2, premium: 2 },
    ],
    payoff: { maxLoss: '主要来自正股下跌', maxProfit: '通常在短 call 附近最好', breakeven: '取决于持股成本和期权净额', shape: '目标价附近增强，过度上涨会受限。' },
    keyRisks: ['多卖 call 管理', '上方收益复杂', '正股下跌风险'],
    teachingNotes: ['适合进阶持股增强教学。'],
  },
  {
    id: 'covered-strangle',
    name: 'Covered Strangle',
    zhName: '备兑宽跨式',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'income',
    supportedInBuilder: false,
    summary: '持股时同时卖出 OTM call 和 OTM put，增加收入但承担接股风险。',
    bestFor: ['愿意加仓也愿意高位卖出', '区间震荡', 'IV 偏高'],
    avoidWhen: ['不想增加持股', '标的可能大跌', '现金或保证金不足'],
    legs: ['持有 100 股', '卖出 OTM call', '卖出 OTM put'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '正股和短 put 下方风险叠加', maxProfit: '上方被 short call 限制', breakeven: '取决于持股成本和总权利金', shape: '区间内收租，下跌会加重持股风险。' },
    keyRisks: ['下跌时可能被迫加仓', '上方被卖出', '保证金要求'],
    teachingNotes: ['不是简单备兑，而是持股加卖 put。'],
  },
  {
    id: 'double-bull-spread',
    name: 'Double Bull Spread',
    zhName: '双牛市价差',
    category: 'bullish',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '组合 bull call spread 和 bull put spread，增强温和看涨暴露。',
    bestFor: ['温和看涨', '想同时使用借方与贷方结构', '能管理四腿'],
    avoidWhen: ['新手', '流动性不足', '不想承担短 put 指派风险'],
    legs: ['牛市看涨价差', '牛市看跌价差'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '取决于两组价差净额', maxProfit: '上方封顶', breakeven: '可有多个', shape: '看涨复合结构，风险来自两侧短腿。' },
    keyRisks: ['四腿成交', '短 put 指派', '收益不一定优于简单价差'],
    teachingNotes: ['适合比较组合叠加，不适合默认推荐。'],
  },
  {
    id: 'double-bear-spread',
    name: 'Double Bear Spread',
    zhName: '双熊市价差',
    category: 'bearish',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '组合 bear put spread 和 bear call spread，增强温和看跌暴露。',
    bestFor: ['温和看跌', '想用复合价差', '能管理四腿'],
    avoidWhen: ['新手', '可能大涨', '价差流动性弱'],
    legs: ['熊市看跌价差', '熊市看涨价差'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '取决于两组价差净额', maxProfit: '下方封顶', breakeven: '可有多个', shape: '看跌复合结构，风险来自上方突破。' },
    keyRisks: ['四腿执行', '短 call 指派', '结构复杂'],
    teachingNotes: ['可以作为组合构造教学。'],
  },
  {
    id: 'bull-call-ladder',
    name: 'Bull Call Ladder',
    zhName: '牛市看涨梯式',
    category: 'bullish',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '在 bull call spread 上额外卖出更高 strike call，降低成本但引入上方风险。',
    bestFor: ['温和看涨但不希望大涨', 'IV 偏高', '高级用户'],
    avoidWhen: ['可能暴涨', '不接受裸 call 风险', '新手'],
    legs: ['买低 call', '卖中 call', '卖高 call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'call', strike: 120, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '上方可能无上限', maxProfit: '中间区间最高', breakeven: '通常有上下两个', shape: '温和上涨有利，大涨危险。' },
    keyRisks: ['裸 call 风险', '保证金', '上方亏损无上限'],
    teachingNotes: ['名字看涨，但不是越涨越好。'],
  },
  {
    id: 'bear-put-ladder',
    name: 'Bear Put Ladder',
    zhName: '熊市看跌梯式',
    category: 'bearish',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '在 bear put spread 上额外卖出更低 strike put，降低成本但引入暴跌风险。',
    bestFor: ['温和看跌但不希望暴跌', 'IV 偏高', '高级用户'],
    avoidWhen: ['可能暴跌', '不接受短 put 风险', '新手'],
    legs: ['买高 put', '卖中 put', '卖低 put'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 80, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '下方风险很高', maxProfit: '中间区间最高', breakeven: '通常有上下两个', shape: '温和下跌有利，暴跌危险。' },
    keyRisks: ['短 put 指派', '暴跌风险', '保证金'],
    teachingNotes: ['名字看跌，但跌太多并不好。'],
  },
  {
    id: 'long-box-spread',
    name: 'Long Box Spread',
    zhName: '盒式价差',
    category: 'greeks',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '用 bull call spread 和 bear put spread 合成接近固定现金流。',
    bestFor: ['理解套利和利率定价', '专业交易', '高流动性指数期权'],
    avoidWhen: ['美式期权提前行权风险高', '手续费高', '不理解融资成本'],
    legs: ['买低 call/卖高 call', '买高 put/卖低 put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 90, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'buy', right: 'put', strike: 110, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '理论固定，实际看成交与行权风险', maxProfit: '理论固定', breakeven: '不按普通方向策略理解', shape: '理论上接近固定到期价值。' },
    keyRisks: ['提前行权', '利率和手续费', '错误成交会严重亏损'],
    teachingNotes: ['主要做教育，不适合作为普通推荐。'],
  },
  {
    id: 'short-box-spread',
    name: 'Short Box Spread',
    zhName: '反向盒式价差',
    category: 'greeks',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '盒式价差的反向结构，常被视作融资或套利相关结构。',
    bestFor: ['专业用户', '理解期权融资', '能控制行权和手续费'],
    avoidWhen: ['零售新手', '美式期权提前行权', '报价不透明'],
    legs: ['卖出盒式价差的四条腿'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 90, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'buy', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'put', strike: 110, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'buy', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '理论固定，实际可能因执行和行权偏离', maxProfit: '理论固定', breakeven: '不按普通方向策略理解', shape: '理论固定现金流的反向。' },
    keyRisks: ['提前行权', '融资成本误判', '成交质量'],
    teachingNotes: ['用于说明 put-call parity，不做普通策略推荐。'],
  },
  {
    id: 'long-guts',
    name: 'Long Guts',
    zhName: '买入内跨式',
    category: 'volatility',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '买 ITM call 和 ITM put，类似 strangle 但用实值期权。',
    bestFor: ['预期大波动', '希望更高内在价值', '理解高成本结构'],
    avoidWhen: ['权利金太贵', '预期波动不足', '流动性弱'],
    legs: ['买入 ITM call', '买入 ITM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 90, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'buy', right: 'put', strike: 110, expiration: expiry, quantity: 1, premium: 12 },
    ],
    payoff: { maxLoss: '总权利金减内在价差', maxProfit: '大幅移动时增加', breakeven: '上下两个', shape: '中间亏损，两端盈利。' },
    keyRisks: ['成本高', 'IV 回落', '需要足够大波动'],
    teachingNotes: ['和 long strangle 是同族波动策略。'],
  },
  {
    id: 'short-guts',
    name: 'Short Guts',
    zhName: '卖出内跨式',
    category: 'volatility',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '卖 ITM call 和 ITM put，类似 short strangle 的高风险变体。',
    bestFor: ['专业卖方', '预期低波动', '能承受保证金'],
    avoidWhen: ['新手', '可能大幅波动', '不接受尾部风险'],
    legs: ['卖出 ITM call', '卖出 ITM put'],
    sampleLegs: [
      { action: 'sell', right: 'call', strike: 90, expiration: expiry, quantity: 1, premium: 12 },
      { action: 'sell', right: 'put', strike: 110, expiration: expiry, quantity: 1, premium: 12 },
    ],
    payoff: { maxLoss: '尾部风险很高', maxProfit: '总权利金减内在价差', breakeven: '上下两个', shape: '中间盈利，两端亏损扩大。' },
    keyRisks: ['尾部风险', '保证金', '指派'],
    teachingNotes: ['作为高阶风险教育即可。'],
  },
  {
    id: 'strap',
    name: 'Strap',
    zhName: '买入偏多跨式',
    category: 'volatility',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '买 2 张 call 和 1 张 put，押注大波动且更偏向上行。',
    bestFor: ['预期大动且偏多', '愿意付更高权利金', '事件交易'],
    avoidWhen: ['IV 太高', '预期波动不足', '不想承担高成本'],
    legs: ['买入 2 张 ATM call', '买入 1 张 ATM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 2, premium: 5 },
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
    ],
    payoff: { maxLoss: '总权利金', maxProfit: '上方理论无限，下方有限', breakeven: '上下两个，上方斜率更高', shape: '两端受益，上方收益更快。' },
    keyRisks: ['成本高', 'IV crush', '需要大幅移动'],
    teachingNotes: ['适合讲方向偏置的波动策略。'],
  },
  {
    id: 'strip',
    name: 'Strip',
    zhName: '买入偏空跨式',
    category: 'volatility',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '买 1 张 call 和 2 张 put，押注大波动且更偏向下行。',
    bestFor: ['预期大动且偏空', '担心下跌跳空', '事件交易'],
    avoidWhen: ['IV 太高', '下跌空间有限', '权利金预算不足'],
    legs: ['买入 1 张 ATM call', '买入 2 张 ATM put'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 2, premium: 5 },
    ],
    payoff: { maxLoss: '总权利金', maxProfit: '下方高但有限，上方无限', breakeven: '上下两个，下方斜率更高', shape: '两端受益，下方收益更快。' },
    keyRisks: ['成本高', 'IV crush', '需要大幅移动'],
    teachingNotes: ['适合讲带方向倾向的 long gamma。'],
  },
  {
    id: 'reverse-iron-condor',
    name: 'Reverse Iron Condor',
    zhName: '反向铁鹰',
    category: 'volatility',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '买入两侧价差，押注价格突破中间区间。',
    bestFor: ['预期大波动', '希望定义风险', '不确定方向'],
    avoidWhen: ['预期横盘', 'IV 太高导致成本贵', '突破幅度不足'],
    legs: ['买 put spread', '买 call spread'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
      { action: 'buy', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 3 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '净支出', maxProfit: '单侧价差宽度 - 净支出', breakeven: '上下两个', shape: '中间亏损，两侧突破盈利封顶。' },
    keyRisks: ['需要足够突破', '双边成本', '盈利封顶'],
    teachingNotes: ['是 iron condor 的买方波动版本。'],
  },
  {
    id: 'reverse-iron-butterfly',
    name: 'Reverse Iron Butterfly',
    zhName: '反向铁蝶',
    category: 'volatility',
    level: 'advanced',
    direction: 'volatile',
    supportedInBuilder: false,
    summary: '买 ATM straddle，同时卖两侧翼，押注离开中心但收益封顶。',
    bestFor: ['预期离开当前价', '希望降低 straddle 成本', '定义风险波动交易'],
    avoidWhen: ['预期小波动', '想保留无限上行', '翼宽太窄'],
    legs: ['买 ATM call/put', '卖 OTM call/put'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 90, expiration: expiry, quantity: 1, premium: 1 },
      { action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 1 },
    ],
    payoff: { maxLoss: '净支出', maxProfit: '翼宽 - 净支出', breakeven: '中心价上下减/加净支出', shape: '中心亏损，两侧盈利封顶。' },
    keyRisks: ['突破不够会亏', '收益封顶', '四腿成交'],
    teachingNotes: ['比 long straddle 成本低，但放弃极端收益。'],
  },
  {
    id: 'double-calendar',
    name: 'Double Calendar Spread',
    zhName: '双日历价差',
    category: 'time_spread',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '同时做 call calendar 和 put calendar，扩大日历策略的目标区间。',
    bestFor: ['短期区间震荡', '关注期限结构', '想比单日历更宽'],
    avoidWhen: ['前腿可能大幅突破', '不理解可变收益', '流动性弱'],
    legs: ['卖近月 call/put', '买远月 call/put'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 95, expiration: '2026-07-31', quantity: 1, premium: 2 },
      { action: 'buy', right: 'put', strike: 95, expiration: '2026-08-21', quantity: 1, premium: 4 },
      { action: 'sell', right: 'call', strike: 105, expiration: '2026-07-31', quantity: 1, premium: 2 },
      { action: 'buy', right: 'call', strike: 105, expiration: '2026-08-21', quantity: 1, premium: 4 },
    ],
    payoff: { maxLoss: '净支出', maxProfit: '可变', breakeven: '可变', shape: '近月到期时在两个 strike 附近较有利。' },
    keyRisks: ['路径依赖', 'IV term structure', '短腿指派'],
    teachingNotes: ['比单日历覆盖范围更宽，但执行更复杂。'],
  },
  {
    id: 'double-diagonal',
    name: 'Double Diagonal Spread',
    zhName: '双对角价差',
    category: 'time_spread',
    level: 'advanced',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '用 call diagonal 和 put diagonal 构造宽区间时间价差。',
    bestFor: ['区间震荡但需要更宽容', '理解期限结构', '能滚动管理'],
    avoidWhen: ['强趋势', '无法管理近月短腿', '价差很宽'],
    legs: ['近月卖两侧 OTM', '远月买更外或相邻保护腿'],
    sampleLegs: [
      { action: 'sell', right: 'put', strike: 95, expiration: '2026-07-31', quantity: 1, premium: 2 },
      { action: 'buy', right: 'put', strike: 90, expiration: '2026-08-21', quantity: 1, premium: 3 },
      { action: 'sell', right: 'call', strike: 105, expiration: '2026-07-31', quantity: 1, premium: 2 },
      { action: 'buy', right: 'call', strike: 110, expiration: '2026-08-21', quantity: 1, premium: 3 },
    ],
    payoff: { maxLoss: '净支出或定义风险，取决于结构', maxProfit: '可变', breakeven: '可变', shape: '价格、时间、IV 共同决定。' },
    keyRisks: ['复杂路径依赖', '期限结构变化', '多腿执行'],
    teachingNotes: ['作为进阶时间价差教学。'],
  },
  {
    id: 'synthetic-long-call',
    name: 'Synthetic Long Call',
    zhName: '合成买入看涨',
    category: 'greeks',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '持有股票并买 put，合成类似 long call 的保护型上涨暴露。',
    bestFor: ['已有股票', '想保留下方保护', '理解合成关系'],
    avoidWhen: ['不持股', '保护成本太高', '不理解合成不等于免费'],
    legs: ['持有 100 股', '买入 put'],
    sampleLegs: [{ action: 'buy', right: 'put', strike: 100, expiration: expiry, quantity: 1, premium: 5 }],
    payoff: { maxLoss: '受 put 保护后有限', maxProfit: '理论上无限', breakeven: '持股成本 + put 成本', shape: '类似买 call，但资金占用不同。' },
    keyRisks: ['保险成本', '正股资金占用', 'IV 影响'],
    teachingNotes: ['用于解释 protective put 与 synthetic call。'],
  },
  {
    id: 'synthetic-long-put',
    name: 'Synthetic Long Put',
    zhName: '合成买入看跌',
    category: 'greeks',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '做空股票并买 call，合成类似 long put 的下跌暴露。',
    bestFor: ['已有空头', '需要上方保护', '理解合成关系'],
    avoidWhen: ['不做空股票', '借券成本高', 'call 保护太贵'],
    legs: ['做空 100 股', '买入 call'],
    sampleLegs: [{ action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 }],
    payoff: { maxLoss: '由 call 限制上方风险', maxProfit: '下跌收益较高', breakeven: '空头入场价 - call 成本', shape: '类似买 put，但涉及股票空头。' },
    keyRisks: ['借券成本', '保护成本', '空头规则'],
    teachingNotes: ['用于解释 synthetic put。'],
  },
  {
    id: 'protective-call',
    name: 'Protective Call',
    zhName: '保护性看涨',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'bearish',
    supportedInBuilder: false,
    summary: '做空股票时买 call 作为上方保护。',
    bestFor: ['已有空头仓位', '担心突然反弹', '想限制空头风险'],
    avoidWhen: ['不做空股票', 'call 成本太高', '不理解空头机制'],
    legs: ['做空 100 股', '买入 call'],
    sampleLegs: [{ action: 'buy', right: 'call', strike: 105, expiration: expiry, quantity: 1, premium: 3 }],
    payoff: { maxLoss: '由 call 限制上方风险', maxProfit: '下跌收益扣除保险成本', breakeven: '空头入场价 - call 成本', shape: '空头下方受益，上方有保护。' },
    keyRisks: ['保险成本', '借券成本', '保护到期'],
    teachingNotes: ['是 protective put 的空头股票镜像。'],
  },
  {
    id: 'cash-backed-call',
    name: 'Cash-Backed Call',
    zhName: '现金担保买股看涨',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '预留现金并买入 call，目标是在上涨时以较低资金风险参与。',
    bestFor: ['想限制投入资本', '看多但保留现金', '理解机会成本'],
    avoidWhen: ['权利金太贵', '不接受到期归零', '需要完整持股权益'],
    legs: ['保留现金', '买入 call'],
    sampleLegs: [{ action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 }],
    payoff: { maxLoss: '权利金', maxProfit: '理论上无限', breakeven: '行权价 + 权利金', shape: '与 long call 接近，但强调现金管理。' },
    keyRisks: ['权利金归零', '现金机会成本', 'IV 回落'],
    teachingNotes: ['OIC 将其列为 acquire stock 相关策略。'],
  },
  {
    id: 'stock-repair',
    name: 'Stock Repair',
    zhName: '股票修复策略',
    category: 'stock_overlay',
    level: 'advanced',
    direction: 'bullish',
    supportedInBuilder: false,
    summary: '持股亏损后，用比例 call spread 降低回本所需股价。',
    bestFor: ['已有亏损持股', '温和反弹预期', '不想额外投入太多'],
    avoidWhen: ['不想上方收益受限', '股票继续下跌风险大', '不理解比例结构'],
    legs: ['持有 100 股', '买入 1 张 call', '卖出 2 张更高 call'],
    sampleLegs: [
      { action: 'buy', right: 'call', strike: 100, expiration: expiry, quantity: 1, premium: 5 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 2, premium: 2 },
    ],
    payoff: { maxLoss: '仍有持股下跌风险', maxProfit: '上方受限', breakeven: '取决于原持股成本和期权结构', shape: '温和反弹时加速修复，上方封顶。' },
    keyRisks: ['继续下跌无充分保护', '上方封顶', '比例 short call 管理'],
    teachingNotes: ['适合持仓管理教学，不是新开仓万能解法。'],
  },
  {
    id: 'zero-cost-collar',
    name: 'Zero-Cost Collar',
    zhName: '零成本领口',
    category: 'stock_overlay',
    level: 'intermediate',
    direction: 'neutral',
    supportedInBuilder: false,
    summary: '用卖 call 收入尽量覆盖买 put 成本，保护持股下跌。',
    bestFor: ['已有持股', '想接近零成本保护', '愿意牺牲上行'],
    avoidWhen: ['不想收益封顶', 'call 收入不足', '保护区间不合理'],
    legs: ['持有股票', '买 put', '卖 call'],
    sampleLegs: [
      { action: 'buy', right: 'put', strike: 95, expiration: expiry, quantity: 1, premium: 2 },
      { action: 'sell', right: 'call', strike: 110, expiration: expiry, quantity: 1, premium: 2 },
    ],
    payoff: { maxLoss: '由 put 限制', maxProfit: '由 short call 封顶', breakeven: '接近持股成本', shape: '下方保护，上方让渡。' },
    keyRisks: ['上行受限', '无法完全零成本', '保护期限有限'],
    teachingNotes: ['比普通 collar 更强调净成本接近 0。'],
  },
]

export const strategyEducationContent: StrategyEducationItem[] = [
  ...coreStrategyEducationContent,
  ...advancedStrategyEducationContent,
  ...marketCatalogStrategyContent,
]
